build: do not fail on unused variables
This breaks our build on the Wii:

```
src/mixer.cpp:35:
/opt/devkitpro/portlibs/ppc/include/vorbis/vorbisfile.h:95:21: error: 'OV_CALLBACKS_STREAMONLY_NOCLOSE' defined but not used [-Werror=unused-variable]
   95 | static ov_callbacks OV_CALLBACKS_STREAMONLY_NOCLOSE = {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/devkitpro/portlibs/ppc/include/vorbis/vorbisfile.h:88:21: error: 'OV_CALLBACKS_STREAMONLY' defined but not used [-Werror=unused-variable]
   88 | static ov_callbacks OV_CALLBACKS_STREAMONLY = {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
/opt/devkitpro/portlibs/ppc/include/vorbis/vorbisfile.h:81:21: error: 'OV_CALLBACKS_NOCLOSE' defined but not used [-Werror=unused-variable]
   81 | static ov_callbacks OV_CALLBACKS_NOCLOSE = {
      |                     ^~~~~~~~~~~~~~~~~~~~
/opt/devkitpro/portlibs/ppc/include/vorbis/vorbisfile.h:74:21: error: 'OV_CALLBACKS_DEFAULT' defined but not used [-Werror=unused-variable]
   74 | static ov_callbacks OV_CALLBACKS_DEFAULT = {
      |                     ^~~~~~~~~~~~~~~~~~~~
```